// Run against HTML generated by test_orcid.py; only Node built-ins are required.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const html = fs.readFileSync(process.argv[2], 'utf8');
const scripts = [...html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)].map(match => match[1]);
const context = vm.createContext({window: {}, console});
for (const script of scripts) vm.runInContext(script, context);
assert.match(html, /<details id="piEditor">/);
assert.match(html, /min="7" max="28"/);

vm.runInContext(`
    globalThis.testMatches = getPIMatches({id: 'https://arxiv.org/abs/2401.12345v9', doi: 'https://doi.org/10.1234/TEST',
        author_orcids: ['0000-0003-2895-6218', '0000-0001-9879-7780']});
    globalThis.nameOnlyMatches = getPIMatches({authors: 'Anna-Christina Eilers, Jenny Greene'});
    globalThis.elements = [
        {dataset: {matchCount: '0', piScore: '100', originalIndex: '0'}},
        {dataset: {matchCount: '2', piScore: '0', originalIndex: '1'}},
        {dataset: {matchCount: '1', piScore: '2', originalIndex: '2'}},
        {dataset: {matchCount: '1', piScore: '3', originalIndex: '3'}},
        {dataset: {matchCount: '1', piScore: '3', originalIndex: '4'}},
        {dataset: {matchCount: '1', piScore: '1', originalIndex: '5'}}
    ].sort(comparePaperElements);
    globalThis.normalizedOldId = normalizeArxiv('https://arxiv.org/pdf/astro-ph/0601001v2.pdf');
    globalThis.invalidOrcid = normalizeOrcid('0000-0003-2895-6219');
    globalThis.cutoff7 = cacheCutoff(7, new Date('2026-09-14T23:59:59Z'));
    globalThis.cutoff14 = cacheCutoff(14, new Date('2026-09-14T00:00:00Z'));
    globalThis.cutoff28 = cacheCutoff(28, new Date('2026-09-14T12:00:00Z'));
    globalThis.originalFilter = filterPapers;
`, context);
assert.deepEqual(Array.from(context.elements, e => Number(e.dataset.originalIndex)), [1, 3, 4, 2, 5, 0]);
assert.deepEqual(Array.from(context.testMatches, p => p.weight), [3, 2]);
assert.equal(context.nameOnlyMatches.length, 0);
assert.equal(context.normalizedOldId, 'astro-ph/0601001');
assert.equal(context.invalidOrcid, '');
assert.equal(context.cutoff7, '2026-09-08');
assert.equal(context.cutoff14, '2026-09-01');
assert.equal(context.cutoff28, '2026-08-18');
assert.throws(() => vm.runInContext(`validatePIs([{name:'PI',orcid:'0000-0003-2895-6219',priority:'High'}])`,context), /Invalid ORCID/);
assert.throws(() => vm.runInContext(`validatePIs([{name:'A',orcid:'0000-0003-2895-6218',priority:'High'},{name:'B',orcid:'0000-0003-2895-6218',priority:'Medium'}])`,context), /more than once/);

// Exercise the actual rendering pipeline with paper elements and inspect its scores/highlights.
vm.runInContext(`
    const records = [
        {id: 'https://arxiv.org/abs/2401.00001', title: 'Keyword first', abstract: 'black hole and obscured', authors: 'Someone', published: '2026-09-14'},
        {id: 'https://arxiv.org/abs/2401.00002', title: 'PI only', abstract: 'No target terms', authors: 'PI', published: '2026-09-14', author_orcids: ['0000-0003-2895-6218']},
        {id: 'https://arxiv.org/abs/2401.00003', title: 'High PI', abstract: 'black hole black hole', authors: 'PI', published: '2026-09-14', author_orcids: ['0000-0002-5612-3427']},
        {id: 'https://arxiv.org/abs/2401.00004', title: 'Highest PI', abstract: 'black hole <script>bad()</script>', authors: 'PI', published: '2026-09-14', author_orcids: ['0000-0003-2895-6218']}
    ];
    currentDataset = records;
    activeKeywords = ['black hole', 'obscured'];
    allPapers = records.map((record, index) => {
        const nodes = {
            '.abstract-text': {dataset: {originalText: record.abstract}},
            '.match-badge': {style: {}},
            '.orcid-matches': {}
        };
        return {dataset: {originalIndex: String(index)}, querySelector: selector => nodes[selector], nodes};
    });
    const enabled = {checked: true};
    globalThis.document = {getElementById: id => id === 'orcidEnabled' ? enabled : {appendChild() {}}};
    filterPapers = () => {};
    applyHighlightsAndRender();
    globalThis.ranked = allPapers.map(p => Number(p.dataset.originalIndex));
    globalThis.escapedAbstract = allPapers.find(p => p.dataset.originalIndex === '3').nodes['.abstract-text'].innerHTML;
    globalThis.scores = currentDataset.map(p => [p.keyword_score, p.pi_score]);
    enabled.checked = false;
    applyHighlightsAndRender();
    globalThis.unweighted = allPapers.map(p => Number(p.dataset.originalIndex));
`, context);
assert.deepEqual(Array.from(context.ranked), [0, 3, 2, 1]);
assert.deepEqual(JSON.parse(JSON.stringify(context.scores)), [[2, 0], [0, 3], [1, 2], [1, 3]]);
assert.ok(context.escapedAbstract.includes('&lt;script&gt;bad()&lt;/script&gt;'));
assert.deepEqual(Array.from(context.unweighted), [0, 2, 3, 1]);

vm.runInContext(`
    currentDataset = [0, 6, 7, 13, 14, 27, 28].map(daysAgo => {
        const date = new Date(); date.setUTCDate(date.getUTCDate() - daysAgo);
        return {published: date.toISOString().slice(0, 10)};
    });
    allPapers = currentDataset.map((_,i) => ({dataset:{originalIndex:String(i)},innerText:'sample'}));
    const summary = {};
    globalThis.document = {getElementById: id => id === 'searchInput' ? {value:''} : summary};
    renderPage = () => {};
    filterPapers = originalFilter;
    activeCacheDays = 7; filterPapers(); globalThis.count7 = filteredPapers.length;
    activeCacheDays = 14; filterPapers(); globalThis.count14 = filteredPapers.length;
    activeCacheDays = 28; filterPapers(); globalThis.count28 = filteredPapers.length;
    datasetMode = 'live'; filterPapers(); globalThis.liveCount = filteredPapers.length;
    trackedPIs = validatePIs([{name:'PI',orcid:'https://orcid.org/0000-0003-2895-6218',priority:'Medium',weight:99}]);
    globalThis.changedWeight = trackedPIs[0].weight;
    globalThis.workKeys = publicWorkKeys({group:[{'external-ids':{'external-id':[
        {'external-id-type':'doi','external-id-value':'10.1234/container','external-id-relationship':'part-of'},
        {'external-id-type':'doi','external-id-value':'10.48550/arXiv.2401.12345','external-id-relationship':'self'}
    ]}}]});
`, context);
assert.deepEqual([context.count7, context.count14, context.count28, context.liveCount], [2,4,6,7]);
assert.equal(context.changedWeight, 1);
assert.deepEqual(Array.from(context.workKeys), ['arxiv:2401.12345', 'doi:10.48550/arxiv.2401.12345']);
vm.runInContext(`
    datasetMode = 'cache'; activeCacheDays = 7; filterPapers();
    globalThis.Blob = class { constructor(parts) { globalThis.downloadedJSON = parts[0]; } };
    globalThis.URL = {createObjectURL: () => 'blob:test', revokeObjectURL() {}};
    document.body = {appendChild() {}, removeChild() {}};
    document.createElement = () => ({click() {}});
    downloadResults();
`, context);
assert.equal(JSON.parse(context.downloadedJSON).length, 2);
console.log('Dashboard JavaScript: ranking, editor validation, cache windows, matching, toggle, exports, and safe highlights passed.');
